export const OPEN_CONTEXT_MENU = 'OPEN_CONTEXT_MENU'
export const CLOSE_CONTEXT_MENU = 'CLOSE_CONTEXT_MENU'

export const ADD_BLOCK = 'ADD_BLOCK'
export const UPDATE_BLOCK = 'UPDATE_BLOCK'
export const DELETE_BLOCK = 'DELETE_BLOCK'
export const RESET_BLOCK_TREE = 'RESET_BLOCK_TREE'

export const ADD_BLOCK_CONTENT = 'ADD_BLOCK_CONTENT'
export const UPDATE_BLOCK_CONTENT = 'UPDATE_BLOCK_CONTENT'
export const DELETE_BLOCK_CONTENT = 'DELETE_BLOCK_CONTENT'

export const ADD_BLOCK_CACHE_ENTRY = 'ADD_BLOCK_CACHE_ENTRY'
export const UPDATE_BLOCK_CACHE_ENTRY = 'UPDATE_BLOCK_CACHE_ENTRY'
export const DELETE_BLOCK_CACHE_ENTRY = 'DELETE_BLOCK_CACHE_ENTRY'

export const ADD_PAGE_PROPERTY = 'ADD_PAGE_PROPERTY'
export const UPDATE_PAGE_PROPERTY = 'UPDATE_PAGE_PROPERTY'
export const DELETE_PAGE_PROPERTY = 'DELETE_PAGE_PROPERTY'

export const LOAD = 'LOAD'

