import EditorContentBlockSecao from '@/components/EditorContentBlockSecao'
import EditorContentBlockTitulo from '@/components/EditorContentBlockTitulo'
import EditorContentBlockTexto from '@/components/EditorContentBlockTexto'
import EditorContentBlockTextoLex from '@/components/EditorContentBlockTextoLex'
import EditorContentBlockListaIcones from '@/components/EditorContentBlockListaIcones'
import EditorContentBlockListaIconesLex from '@/components/EditorContentBlockListaIconesLex'
import EditorContentBlockBlocosIcones from '@/components/EditorContentBlockBlocosIcones'
import EditorContentBlockBlocosIconesLex from '@/components/EditorContentBlockBlocosIconesLex'
import EditorContentBlockBotao from '@/components/EditorContentBlockBotao'
import EditorContentBlockYouTube from '@/components/EditorContentBlockYouTube'
import EditorContentBlockBoxConhecer from '@/components/EditorContentBlockBoxConhecer'
import EditorContentBlockBoxDescontos from '@/components/EditorContentBlockBoxDescontos'
import EditorContentBlockQrCodeCampus from '@/components/EditorContentBlockQrCodeCampus'
import EditorContentBlockQrCodeCic from '@/components/EditorContentBlockQrCodeCic'
import EditorContentBlockQrCodeSjp from '@/components/EditorContentBlockQrCodeSjp'
import EditorContentBlockQrCodeLondrina from '@/components/EditorContentBlockQrCodeLondrina'

export default {
  DND_EDITOR_SIDEBAR_BLOCK_SECAO: EditorContentBlockSecao,
  DND_EDITOR_SIDEBAR_BLOCK_TITULO: EditorContentBlockTitulo,
  DND_EDITOR_SIDEBAR_BLOCK_TEXTO: EditorContentBlockTexto,
  DND_EDITOR_SIDEBAR_BLOCK_TEXTO_LEX: EditorContentBlockTextoLex,
  DND_EDITOR_SIDEBAR_BLOCK_LISTA_ICONES: EditorContentBlockListaIcones,
  DND_EDITOR_SIDEBAR_BLOCK_LISTA_ICONES_LEX: EditorContentBlockListaIconesLex,
  DND_EDITOR_SIDEBAR_BLOCK_BLOCOS_ICONES: EditorContentBlockBlocosIcones,
  DND_EDITOR_SIDEBAR_BLOCK_BLOCOS_ICONES_LEX: EditorContentBlockBlocosIconesLex,
  DND_EDITOR_SIDEBAR_BLOCK_BOTAO: EditorContentBlockBotao,
  DND_EDITOR_SIDEBAR_BLOCK_YOUTUBE: EditorContentBlockYouTube,
  DND_EDITOR_SIDEBAR_BLOCK_BOX_CONHECER: EditorContentBlockBoxConhecer,
  DND_EDITOR_SIDEBAR_BLOCK_BOX_DESCONTOS: EditorContentBlockBoxDescontos,
  DND_EDITOR_SIDEBAR_BLOCK_QR_CODE_CAMPUS: EditorContentBlockQrCodeCampus,
  DND_EDITOR_SIDEBAR_BLOCK_QR_CODE_CIC: EditorContentBlockQrCodeCic,
  DND_EDITOR_SIDEBAR_BLOCK_QR_CODE_SJP: EditorContentBlockQrCodeSjp,
  DND_EDITOR_SIDEBAR_BLOCK_QR_CODE_LONDRINA: EditorContentBlockQrCodeLondrina,
}